In [1]:
import numpy as np
from scipy.linalg import null_space

In [2]:
def column_space(matrix):
    """
    Returns the column space of matrix (set of linearly independent columnns)
    """

    # Perform QR decomposition to get the orthogonal basis for the column space
    Q,R = np.linalg.qr(matrix)

    # Extract the number of independent columnns by checking the rank of R
    rank = np.linalg.matrix_rank(matrix)

    # The first rank columns of Q from the basis for the column space
    col_space = Q[:,:rank]
    print(f"Column space(Basis):\n{col_space}\n")
    return col_space

In [3]:
# Function to compute null space of the matrix
def compute_null_space(matrix):
    null_sp = null_space(matrix)
    if null_sp.size == 0:
        print("The null space is a trivial( only contain the zero vector).")
    else:
        print(f"Null space (Basis):\n{null_sp}\n")
    return null_sp

In [ ]:
# A function to compute rank of the matrix
def compute_rank(matrix):
    """ Return the rank of a matrix"""
    rank = np.linalg.matrix_rank(matrix)
    print(f"The rank of matrix:{rank}\n")
    return rank
    

In [4]:
# Example of a matrix

matrix = np.array([
    [2,4,1],
    [0,1,-1],
    [-2,-4,5]
])

print("Matrix:\n")
print(matrix)

Matrix:

[[ 2  4  1]
 [ 0  1 -1]
 [-2 -4  5]]
